# Generated by Django 5.0.3 on 2024-06-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_en",
            field=models.CharField(max_length=128, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_ru",
            field=models.CharField(max_length=128, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_uz",
            field=models.CharField(max_length=128, null=True, verbose_name="Title"),
        ),
    ]
