# Generated by Django 5.0.3 on 2024-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
