# Generated by Django 4.2 on 2024-10-23 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0002_lostpet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LostPet",
        ),
    ]
