# Generated by Django 5.0.3 on 2024-06-29 15:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_community_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="description"
            ),
        ),
    ]
