# Generated by Django 4.2 on 2024-10-23 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0003_animaltype_lostanimal_delete_lostpet"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=32, verbose_name="Title")),
                (
                    "title_uz",
                    models.CharField(max_length=32, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=32, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=32, null=True, verbose_name="Title"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LostAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="lost_animals/")),
                (
                    "animal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.animaltype",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
