# Generated by Django 5.0.3 on 2024-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_community_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
