# Generated by Django 5.0.3 on 2024-06-29 16:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_alter_community_title_alter_community_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description"
            ),
        ),
    ]
