# Generated by Django 4.2 on 2024-10-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_animaltype_lostanimal"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=32, verbose_name="Title")),
                (
                    "title_uz",
                    models.CharField(max_length=32, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=32, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=32, null=True, verbose_name="Title"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lostanimal",
            name="gender_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.gendertype",
            ),
        ),
    ]
