# Generated by Django 5.0.3 on 2024-06-29 16:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_alter_community_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="description_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="description_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="description_uz",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Description"
            ),
        ),
    ]
