# Generated by Django 4.2 on 2024-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_lostanimal_phone_number_alter_lostanimal_gender_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostanimal",
            name="phone_number",
            field=models.CharField(max_length=32),
        ),
    ]
