# Generated by Django 4.2 on 2024-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0007_alter_lostanimal_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostanimal",
            name="date_lost",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="lostanimal",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AddField(
            model_name="lostanimal",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
    ]
