# Generated by Django 4.2 on 2024-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0008_lostanimal_date_lost_lostanimal_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostanimal",
            name="date_lost",
            field=models.DateField(blank=True, null=True),
        ),
    ]
