# Generated by Django 5.0.3 on 2024-10-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0009_alter_lostanimal_date_lost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(
                blank=True, max_length=128, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="description_en",
            field=models.TextField(
                blank=True, max_length=128, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="description_ru",
            field=models.TextField(
                blank=True, max_length=128, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="description_uz",
            field=models.TextField(
                blank=True, max_length=128, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_en",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_ru",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="community",
            name="title_uz",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
    ]
