# Generated by Django 5.0.3 on 2024-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0011_alter_community_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="community",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="community",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="community",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
