# Generated by Django 4.2.5 on 2023-10-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=5)),
                ('address', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=32)),
                ('otp', models.CharField(max_length=32)),
                ('invalid_attempts', models.PositiveIntegerField(default=0)),
                ('purpose', models.CharField(choices=[('reset_password', 'Reset password')], max_length=64)),
                ('validated', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
