# Generated by Django 4.2.5 on 2023-11-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationsession",
            options={
                "verbose_name": "verification session",
                "verbose_name_plural": "verification sessions",
            },
        ),
    ]
