# Generated by Django 5.0.2 on 2024-02-26 05:23

import ckeditor_uploader.fields
import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('title', models.CharField(choices=[('Hashar', 'Hashar'), ('Animals Feeding', 'Animals Feeding')], default='Hashar', max_length=255, unique=True, verbose_name='Event Type')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=255, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Tashkent City', 'Tashkent City'), ('Tashkent Region', 'Tashkent Region'), ('Andijan', 'Andijan Region'), ('Namangan', 'Namangan Region'), ('Fergana', 'Fergana Region'), ('Sirdarya', 'Sirdarya Region'), ('Jizzah', 'Jizzah Region'), ('Samarqand', 'Samarqand Region'), ('Qashqadarya', 'Qashqadarya Region'), ('Surkhandarya', 'Surkhandarya Region'), ('Bukhara', 'Bukhara Region'), ('Navoi', 'Navoi Region'), ('Xorazm', 'Xorazm Region'), ('Karakalpak Republik', 'Karakalpak Republik')], default='Tashkent City', max_length=255, unique=True, verbose_name='Street name (Arentir)')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='common.media', verbose_name='Thumbnail image')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'Blog',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('location', location_field.models.plain.PlainLocationField(default='41.311151,69.279737', max_length=63)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('arentir', models.CharField(max_length=255, verbose_name='Street name (Arentir)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='common.event')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='common.region')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Position',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.position'),
        ),
    ]
