# Generated by Django 4.2 on 2024-03-31 10:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_active_en",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="event",
            name="is_active_ru",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="event",
            name="is_active_uz",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                choices=[("Hashar", "Hashar"), ("Animals Feeding", "Animals Feeding")],
                default="Hashar",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Event Type",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_ru",
            field=models.CharField(
                choices=[("Hashar", "Hashar"), ("Animals Feeding", "Animals Feeding")],
                default="Hashar",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Event Type",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_uz",
            field=models.CharField(
                choices=[("Hashar", "Hashar"), ("Animals Feeding", "Animals Feeding")],
                default="Hashar",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Event Type",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="arentir_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Street name (Arentir)"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="arentir_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Street name (Arentir)"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="arentir_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Street name (Arentir)"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="description_en",
            field=models.TextField(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="description_ru",
            field=models.TextField(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="description_uz",
            field=models.TextField(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="position",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="position",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="content_ru",
            field=models.TextField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="content_uz",
            field=models.TextField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="short_description_en",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="short_description_ru",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="short_description_uz",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ru",
            field=models.CharField(max_length=256, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_uz",
            field=models.CharField(max_length=256, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="region",
            name="type_en",
            field=models.CharField(
                choices=[
                    ("Tashkent City", "Tashkent City"),
                    ("Tashkent Region", "Tashkent Region"),
                    ("Andijan", "Andijan Region"),
                    ("Namangan", "Namangan Region"),
                    ("Fergana", "Fergana Region"),
                    ("Sirdarya", "Sirdarya Region"),
                    ("Jizzah", "Jizzah Region"),
                    ("Samarqand", "Samarqand Region"),
                    ("Qashqadarya", "Qashqadarya Region"),
                    ("Surkhandarya", "Surkhandarya Region"),
                    ("Bukhara", "Bukhara Region"),
                    ("Navoi", "Navoi Region"),
                    ("Xorazm", "Xorazm Region"),
                    ("Karakalpak Republik", "Karakalpak Republik"),
                ],
                default="Tashkent City",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Street name (Arentir)",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="type_ru",
            field=models.CharField(
                choices=[
                    ("Tashkent City", "Tashkent City"),
                    ("Tashkent Region", "Tashkent Region"),
                    ("Andijan", "Andijan Region"),
                    ("Namangan", "Namangan Region"),
                    ("Fergana", "Fergana Region"),
                    ("Sirdarya", "Sirdarya Region"),
                    ("Jizzah", "Jizzah Region"),
                    ("Samarqand", "Samarqand Region"),
                    ("Qashqadarya", "Qashqadarya Region"),
                    ("Surkhandarya", "Surkhandarya Region"),
                    ("Bukhara", "Bukhara Region"),
                    ("Navoi", "Navoi Region"),
                    ("Xorazm", "Xorazm Region"),
                    ("Karakalpak Republik", "Karakalpak Republik"),
                ],
                default="Tashkent City",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Street name (Arentir)",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="type_uz",
            field=models.CharField(
                choices=[
                    ("Tashkent City", "Tashkent City"),
                    ("Tashkent Region", "Tashkent Region"),
                    ("Andijan", "Andijan Region"),
                    ("Namangan", "Namangan Region"),
                    ("Fergana", "Fergana Region"),
                    ("Sirdarya", "Sirdarya Region"),
                    ("Jizzah", "Jizzah Region"),
                    ("Samarqand", "Samarqand Region"),
                    ("Qashqadarya", "Qashqadarya Region"),
                    ("Surkhandarya", "Surkhandarya Region"),
                    ("Bukhara", "Bukhara Region"),
                    ("Navoi", "Navoi Region"),
                    ("Xorazm", "Xorazm Region"),
                    ("Karakalpak Republik", "Karakalpak Republik"),
                ],
                default="Tashkent City",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Street name (Arentir)",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_ru",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_uz",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
