# Generated by Django 5.0.3 on 2024-04-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_event_is_active_en_event_is_active_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
