# Generated by Django 5.0.3 on 2024-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_remove_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Event Type"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Event Type"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Event Type"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Event Type"
            ),
        ),
    ]
