# Generated by Django 5.0.3 on 2024-04-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_region_type_alter_region_type_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "content",
                    models.TextField(verbose_name="Content"),
                ),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
    ]
