# Generated by Django 5.0.3 on 2024-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="content_en",
            field=models.TextField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="content_ru",
            field=models.TextField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="content_uz",
            field=models.TextField(
                null=True, verbose_name="Content"
            ),
        ),
    ]
