# Generated by Django 5.0.3 on 2024-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_about_content_en_about_content_ru_about_content_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="title",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
