# Generated by Django 5.0.3 on 2024-04-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "common",
            "0009_alter_about_title_alter_tag_title_alter_tag_title_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="title_en",
            field=models.CharField(max_length=128, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_ru",
            field=models.CharField(max_length=128, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_uz",
            field=models.CharField(max_length=128, null=True, verbose_name="Title"),
        ),
    ]
