# Generated by Django 5.0.3 on 2024-07-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_usersavedposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to="event/"),
        ),
    ]
