# Generated by Django 5.0.3 on 2024-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
