# Generated by Django 5.0.3 on 2024-09-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_position_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="position"),
        ),
    ]
