# Generated by Django 5.0.3 on 2024-09-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_alter_position_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="posts/"),
        ),
    ]
