# Generated by Django 4.2.21 on 2025-05-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_about_content_alter_about_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
