# Generated by Django 4.2.21 on 2025-05-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_alter_position_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="region",
            old_name="type",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="type_en",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="type_ru",
            new_name="title_ru",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="type_uz",
            new_name="title_uz",
        ),
    ]
