# Generated by Django 5.0.2 on 2024-03-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_event_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='private_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='raw_password',
        ),
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default=1, upload_to='users/', verbose_name='avatar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
